export const restaurants = [
    {
        info: {
            id: '32942',
            name: 'Bakingo',
            cloudinaryImageId: 'hsylepkuygu6k8mryapk',
            locality: 'Gautam Buddha Nagar',
            areaName: 'Sector - 60',
            costForTwo: '₹300 for two',
            cuisines: ['Bakery', 'Desserts', 'Beverages', 'Snacks'],
            avgRating: 4.4,
            feeDetails: {
                restaurantId: '32942',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 7900 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 7900,
            },
            parentId: '3818',
            avgRatingString: '4.4',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 36,
                lastMileTravel: 5,
                serviceability: 'SERVICEABLE',
                slaString: '36 mins',
                lastMileTravelString: '5.0 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 01:00:00', opened: true },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/bakingo-gautam-buddha-nagar-sector-60-noida-1-32942',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '39294',
            name: 'KFC',
            cloudinaryImageId: 'f01666ac73626461d7455d9c24005cd4',
            locality: 'P Block',
            areaName: 'Sector 18',
            costForTwo: '₹450 for two',
            cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
            avgRating: 4,
            feeDetails: {
                restaurantId: '39294',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '547',
            avgRatingString: '4.0',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 27,
                lastMileTravel: 1.8,
                serviceability: 'SERVICEABLE',
                slaString: '27 mins',
                lastMileTravelString: '1.8 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 02:00:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: '40% OFF', subHeader: 'UPTO ₹80' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/kfc-p-block-sector-18-noida-1-39294',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '253710',
            name: "McDonald's",
            cloudinaryImageId: '6dc3ed2ca21d71acff7c2a51dfe4c720',
            locality: 'Sector 18',
            areaName: 'Sector 18',
            costForTwo: '₹400 for two',
            cuisines: ['American'],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '253710',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '630',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 31,
                lastMileTravel: 1.9,
                serviceability: 'SERVICEABLE',
                slaString: '31 mins',
                lastMileTravelString: '1.9 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 00:00:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: '10% OFF', subHeader: 'UPTO ₹40' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/mcdonalds-sector-18-noida-1-253710',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '223412',
            name: 'Burger King',
            cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
            locality: 'C Block',
            areaName: 'Gautam Buddha Nagar',
            costForTwo: '₹350 for two',
            cuisines: ['Burgers', 'American'],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '223412',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '166',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 28,
                lastMileTravel: 2.3,
                serviceability: 'SERVICEABLE',
                slaString: '28 mins',
                lastMileTravelString: '2.3 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 05:00:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/burger-king-c-block-gautam-buddha-nagar-noida-1-223412',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '377799',
            name: 'Pizza Hut',
            cloudinaryImageId: '2b4f62d606d1b2bfba9ba9e5386fabb7',
            locality: 'G Block',
            areaName: 'Sector 27',
            costForTwo: '₹350 for two',
            cuisines: ['Pizzas'],
            avgRating: 3.8,
            feeDetails: {
                restaurantId: '377799',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '721',
            avgRatingString: '3.8',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 31,
                lastMileTravel: 0.4,
                serviceability: 'SERVICEABLE',
                slaString: '31 mins',
                lastMileTravelString: '0.4 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 01:00:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: 'FREE ITEM' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/pizza-hut-g-block-sector-27-noida-1-377799',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '24165',
            name: "Domino's Pizza",
            cloudinaryImageId: 'aghc63r6dofcc4kmgk7b',
            locality: 'Sector 18',
            areaName: 'Sector 18',
            costForTwo: '₹400 for two',
            cuisines: ['Pizzas', 'Italian', 'Pastas', 'Desserts'],
            avgRating: 4.1,
            feeDetails: {
                restaurantId: '24165',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 4100 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 4100,
            },
            parentId: '2456',
            avgRatingString: '4.1',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 25,
                serviceability: 'SERVICEABLE',
                slaString: '25 mins',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 02:59:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: '25% OFF', discountTag: 'FLAT DEAL' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/dominos-pizza-sector-18-noida-1-24165',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '413891',
            name: 'Louis Burger',
            cloudinaryImageId: '19d3d352cc815b9d88b22617b41fa97b',
            locality: 'B Block',
            areaName: 'Sector 4',
            costForTwo: '₹600 for two',
            cuisines: ['Burgers', 'American', 'Fast Food'],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '413891',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '22485',
            avgRatingString: '4.2',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 34,
                lastMileTravel: 1.2,
                serviceability: 'SERVICEABLE',
                slaString: '34 mins',
                lastMileTravelString: '1.2 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 04:00:00', opened: true },
            badges: {
                imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹125 OFF',
                subHeader: 'ABOVE ₹249',
                discountTag: 'FLAT DEAL',
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/louis-burger-b-block-sector-4-noida-1-413891',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '54412',
            name: 'Hira Sweets',
            cloudinaryImageId: 'mhdozglimuncn5sydb3l',
            locality: 'B Block',
            areaName: 'Sector 18',
            costForTwo: '₹600 for two',
            cuisines: [
                'North Indian',
                'South Indian',
                'Chinese',
                'Continental',
                'Bakery',
                'Street Food',
                'Sweets',
                'Desserts',
                'Beverages',
            ],
            avgRating: 4.2,
            veg: true,
            feeDetails: {
                restaurantId: '54412',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5600 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5600,
            },
            parentId: '5155',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 25,
                lastMileTravel: 1.5,
                serviceability: 'SERVICEABLE',
                slaString: '25 mins',
                lastMileTravelString: '1.5 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                imageBadges: [
                    {
                        imageId: 'v1695133679/badges/Pure_Veg111.png',
                        description: 'pureveg',
                    },
                ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: 'pureveg',
                                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/hira-sweets-b-block-sector-18-noida-1-54412',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '26795',
            name: 'Theobroma',
            cloudinaryImageId: 'b033728dcb0101ceb19bff0e1e1f6474',
            locality: 'Sector 18',
            areaName: 'Sector 18',
            costForTwo: '₹800 for two',
            cuisines: ['Bakery', 'Desserts'],
            avgRating: 4.5,
            feeDetails: {
                restaurantId: '26795',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '1040',
            avgRatingString: '4.5',
            totalRatingsString: '5K+',
            sla: {
                deliveryTime: 37,
                lastMileTravel: 2,
                serviceability: 'SERVICEABLE',
                slaString: '37 mins',
                lastMileTravelString: '2.0 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:00:00', opened: true },
            badges: {
                imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '25% OFF',
                subHeader: 'ABOVE ₹159',
                discountTag: 'FLAT DEAL',
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/theobroma-sector-18-noida-1-26795',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '12489',
            name: 'Subway',
            cloudinaryImageId: '1ace5fa65eff3e1223feb696c956b38b',
            locality: "Near Mc Donald's",
            areaName: 'Sector 16',
            costForTwo: '₹350 for two',
            cuisines: ['Salads', 'Snacks', 'Desserts', 'Beverages'],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '12489',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '2',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 35,
                lastMileTravel: 2.7,
                serviceability: 'SERVICEABLE',
                slaString: '35 mins',
                lastMileTravelString: '2.7 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: 'guiltfree/GF_Logo_android_3x',
                        shortDescription: 'options available',
                        fontColor: '#7E808C',
                    },
                ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId: 'guiltfree/GF_Logo_android_3x',
                                    shortDescription: 'options available',
                                },
                            },
                        ],
                    },
                },
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/subway-near-mc-donalds-sector-16-noida-1-12489',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '237330',
            name: 'Behrouz Biryani',
            cloudinaryImageId: '89fccaa76f2f760e2742b9e53d32bb69',
            locality: 'D Block',
            areaName: 'Sector 2',
            costForTwo: '₹500 for two',
            cuisines: [
                'Biryani',
                'Mughlai',
                'North Indian',
                'Lucknowi',
                'Hyderabadi',
                'Kebabs',
                'Desserts',
                'Beverages',
            ],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '237330',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '1803',
            avgRatingString: '4.2',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 37,
                lastMileTravel: 2.1,
                serviceability: 'SERVICEABLE',
                slaString: '37 mins',
                lastMileTravelString: '2.1 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: { header: '60% OFF', subHeader: 'UPTO ₹120' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/behrouz-biryani-d-block-sector-2-noida-1-237330',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '237336',
            name: 'LunchBox - Meals and Thalis',
            cloudinaryImageId: '4edcfc66d91018d69894941ebb3c8d16',
            locality: 'D Block',
            areaName: 'Sector 2',
            costForTwo: '₹200 for two',
            cuisines: [
                'Biryani',
                'North Indian',
                'Punjabi',
                'Healthy Food',
                'Desserts',
                'Beverages',
            ],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '237336',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '4925',
            avgRatingString: '4.2',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 37,
                lastMileTravel: 2.1,
                serviceability: 'SERVICEABLE',
                slaString: '37 mins',
                lastMileTravelString: '2.1 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: 'guiltfree/GF_Logo_android_3x',
                        shortDescription: 'options available',
                        fontColor: '#7E808C',
                    },
                ],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId: 'guiltfree/GF_Logo_android_3x',
                                    shortDescription: 'options available',
                                },
                            },
                        ],
                    },
                },
            },
            aggregatedDiscountInfoV3: { header: 'ITEMS', subHeader: 'AT ₹149' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-d-block-sector-2-noida-1-237336',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '237329',
            name: 'Faasos - Wraps & Rolls',
            cloudinaryImageId: 'af33b81798b11deba338e94b7585d348',
            locality: 'D Block',
            areaName: 'Sector 2',
            costForTwo: '₹200 for two',
            cuisines: [
                'Kebabs',
                'Fast Food',
                'Snacks',
                'North Indian',
                'American',
                'Healthy Food',
                'Desserts',
                'Beverages',
            ],
            avgRating: 4.1,
            feeDetails: {
                restaurantId: '237329',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 3800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 3800,
            },
            parentId: '21809',
            avgRatingString: '4.1',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 37,
                lastMileTravel: 2.1,
                serviceability: 'SERVICEABLE',
                slaString: '37 mins',
                lastMileTravelString: '2.1 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: 'guiltfree/GF_Logo_android_3x',
                        shortDescription: 'options available',
                        fontColor: '#7E808C',
                    },
                ],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId: 'guiltfree/GF_Logo_android_3x',
                                    shortDescription: 'options available',
                                },
                            },
                        ],
                    },
                },
            },
            aggregatedDiscountInfoV3: { header: 'ITEMS', subHeader: 'AT ₹99' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/faasos-wraps-and-rolls-d-block-sector-2-noida-1-237329',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '326637',
            name: 'Khadak Singh Da Dhaba',
            cloudinaryImageId: '8144bf37947c161953f656308d1bfc30',
            locality: 'Golf Course',
            areaName: 'Sector 37',
            costForTwo: '₹300 for two',
            cuisines: ['North Indian', 'Mughlai', 'Chinese', 'Tandoor', 'Indian'],
            avgRating: 4,
            feeDetails: {
                restaurantId: '326637',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 4100 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 4100,
            },
            parentId: '13170',
            avgRatingString: '4.0',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 30,
                lastMileTravel: 2.4,
                serviceability: 'SERVICEABLE',
                slaString: '30 mins',
                lastMileTravelString: '2.4 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/khadak-singh-da-dhaba-golf-course-sector-37-noida-1-326637',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '16829',
            name: "Berco's -If You Love Chinese",
            cloudinaryImageId: '3344b8e498281fdcd461dc1b5f3b44d5',
            locality: 'Sector 12',
            areaName: 'Sector 12',
            costForTwo: '₹600 for two',
            cuisines: [
                'Asian',
                'Thai',
                'Chinese',
                'Seafood',
                'Desserts',
                'Beverages',
            ],
            avgRating: 4.2,
            feeDetails: {
                restaurantId: '16829',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '471817',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 23,
                lastMileTravel: 2.1,
                serviceability: 'SERVICEABLE',
                slaString: '23 mins',
                lastMileTravelString: '2.1 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: { header: '30% OFF', subHeader: 'UPTO ₹75' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/bercos-if-you-love-chinese-sector-12-noida-1-16829',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '387946',
            name: 'Burgerama',
            cloudinaryImageId: '1d52387b37dbec1712d0142aec3421a6',
            locality: 'B Block',
            areaName: 'Sector 4',
            costForTwo: '₹600 for two',
            cuisines: ['American'],
            avgRating: 4.1,
            feeDetails: {
                restaurantId: '387946',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '8993',
            avgRatingString: '4.1',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 34,
                lastMileTravel: 1.2,
                serviceability: 'SERVICEABLE',
                slaString: '34 mins',
                lastMileTravelString: '1.2 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:59:00', opened: true },
            badges: {
                imageBadges: [{ imageId: 'newg.png', description: 'Gourmet' }],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            { attributes: { description: 'Gourmet', imageId: 'newg.png' } },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: { header: '50% OFF', subHeader: 'UPTO ₹100' },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/burgerama-b-block-sector-4-noida-1-387946',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '43913',
            name: 'Wakhra Swaad',
            cloudinaryImageId: '06614d33a0adb57e8baf7c0f736937da',
            locality: 'L Block',
            areaName: 'Sector 11',
            costForTwo: '₹500 for two',
            cuisines: ['North Indian', 'Mughlai', 'Biryani', 'Chinese'],
            avgRating: 4.1,
            feeDetails: {
                restaurantId: '43913',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '6455',
            avgRatingString: '4.1',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 30,
                lastMileTravel: 2.9,
                serviceability: 'SERVICEABLE',
                slaString: '30 mins',
                lastMileTravelString: '2.9 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 01:59:00', opened: true },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            aggregatedDiscountInfoV3: {
                header: '₹125 OFF',
                subHeader: 'ABOVE ₹249',
                discountTag: 'FLAT DEAL',
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/wakhra-swaad-l-block-sector-11-noida-1-43913',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '21127',
            name: 'Nazeer Foods',
            cloudinaryImageId: '6aa38b251b1ee1662961a6dc19e41e95',
            locality: 'G Block',
            areaName: 'Sector 18',
            costForTwo: '₹400 for two',
            cuisines: ['North Indian', 'Biryani', 'Mughlai', 'Snacks'],
            avgRating: 3.9,
            feeDetails: {
                restaurantId: '21127',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '2351',
            avgRatingString: '3.9',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 32,
                lastMileTravel: 1.7,
                serviceability: 'SERVICEABLE',
                slaString: '32 mins',
                lastMileTravelString: '1.7 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:00:00', opened: true },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: { imageBased: {}, textBased: {}, textExtendedBadges: {} },
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/nazeer-foods-g-block-sector-18-noida-1-21127',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '523688',
            name: "Nirula's",
            cloudinaryImageId: '94c82b9d46792c198fff64899ff05bd2',
            locality: 'Shaheed Arjun Sardana Marg',
            areaName: 'Sector 27',
            costForTwo: '₹500 for two',
            cuisines: [
                'Pizzas',
                'Burgers',
                'Ice Cream',
                'North Indian',
                'Fast Food',
                'Pastas',
                'Beverages',
            ],
            avgRating: 4,
            feeDetails: {
                restaurantId: '523688',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 5800 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 5800,
            },
            parentId: '1738',
            avgRatingString: '4.0',
            totalRatingsString: '100+',
            sla: {
                deliveryTime: 25,
                lastMileTravel: 0.5,
                serviceability: 'SERVICEABLE',
                slaString: '25 mins',
                lastMileTravelString: '0.5 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-01 23:00:00', opened: true },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: 'guiltfree/GF_Logo_android_3x',
                        shortDescription: 'options available',
                        fontColor: '#7E808C',
                    },
                ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId: 'guiltfree/GF_Logo_android_3x',
                                    shortDescription: 'options available',
                                },
                            },
                        ],
                    },
                },
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/nirulas-shaheed-arjun-sardana-marg-sector-27-noida-1-523688',
            type: 'WEBLINK',
        },
    },
    {
        info: {
            id: '69469',
            name: 'Pasta la Vista',
            cloudinaryImageId: 'ba665f892177fdbf0a8daa5fff3ac29f',
            locality: 'D Block',
            areaName: 'Sector 7',
            costForTwo: '₹300 for two',
            cuisines: ['Continental', 'Italian'],
            avgRating: 4,
            veg: true,
            feeDetails: {
                restaurantId: '69469',
                fees: [
                    { name: 'BASE_DISTANCE', fee: 4900 },
                    { name: 'BASE_TIME' },
                    { name: 'ANCILLARY_SURGE_FEE' },
                ],
                totalFee: 4900,
            },
            parentId: '2372',
            avgRatingString: '4.0',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 27,
                lastMileTravel: 3.6,
                serviceability: 'SERVICEABLE',
                slaString: '27 mins',
                lastMileTravelString: '3.6 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: { nextCloseTime: '2023-12-02 02:00:00', opened: true },
            badges: {
                imageBadges: [
                    {
                        imageId: 'v1695133679/badges/Pure_Veg111.png',
                        description: 'pureveg',
                    },
                ],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: 'pureveg',
                                    imageId: 'v1695133679/badges/Pure_Veg111.png',
                                },
                            },
                        ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹125 OFF',
                subHeader: 'ABOVE ₹249',
                discountTag: 'FLAT DEAL',
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {},
        cta: {
            link: 'https://www.swiggy.com/restaurants/pasta-la-vista-d-block-sector-7-noida-1-69469',
            type: 'WEBLINK',
        },
    },
];
